# Generated by Django 4.2.6 on 2023-10-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.AlterField(
            model_name='car',
            name='reg_number',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
