# Generated by Django 4.2.6 on 2023-10-31 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carparking', '0002_remove_car_id_alter_car_reg_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='slot',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carparking.slot'),
        ),
    ]
